### ISSUE TITLE
many links in `readme.org` are dead

### ISSUE THREAD

**Issue by benthamite** [mclear-tools/dotemacs#3]
Thanks for making your config publicly available! I came here via a Reddit [comment](https://www.reddittorjg6rue252oqsxryoxengawnmo46qy4kyii5wtqnwfj4ooad.onion/r/orgmode/comments/td76wz/comment/i0jru83/) linking to your `org-cite` config. Unfortunately, that link is dead, and so are many of the links [here](https://github.com/mclear-tools/dotemacs/blob/master/README.org).

(Feel free to ignore this.)

**Comment by mclearc** [comment]
Thanks! These were all left over from when I had my dotemacs integrated with Lambda Emacs. You can find documentation for its modules here: https://github.com/Lambda-Emacs/lambda-emacs/blob/main/DOCUMENTATION.org and a list of some of its functionality here: https://github.com/Lambda-Emacs/lambda-emacs#𝛌-emacs-modules
